GET http://localhost:8080/v1/api/film/title/maude
Accept: application/json

###

GET http://localhost:8080/v1/api/film/actor/ed chase
Accept: application/json

###

GET http://localhost:8080/v1/api/film/getFilm?title=Maude&actor=""
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/v1/api/film/getFilmAll?country=Australia
Accept: application/json
Content-Type: application/json


###

GET http://localhost:8080/v1/api/film/getFilmMostRented?country=Australia
Accept: application/json
Content-Type: application/json