POST http://localhost:8080/v1/api/customer/post
Accept: application/json
Content-Type: application/json

{
  "store_id": 2,
  "first_name": "Mark",
  "last_name": "Hammil",
  "email": "mhmm@gmail.com",
  "address_id": 2,
  "active": 1
}


###
GET http://localhost:8080/v1/api/customer/getEmail?nombre=MARY&appel=SMITH
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/v1/api/customer/getAddress?customer=4
Accept: application/json
Content-Type: application/json

###