POST http://localhost:8080/v1/api/customer/post
Accept: application/json
Content-Type: application/json

{
  "store_id": 2,
  "first_name": "Mark",
  "last_name": "Hammil",
  "email": "mhmm@gmail.com",
  "address_id": 2,
  "active": 1
}


###
GET http://localhost:8080/v1/api/customer/getEmail?nombre=MARY&appel=SMITH
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/v1/api/customer/getAddress?customer=4
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/v1/api/customer/postNewRent
Accept: application/json
Content-Type: application/json

{
  "film_id": 1,
  "store_id": 1,
  "payment_id": 2,
  "customer_id": 2,
  "staff_id": 1,
  "rental_id": 1,
  "amount": 10,
  "return_date": "2021-12-27T12:26:30.107"
}

###

POST http://localhost:8080/v1/api/customer/postRental
Accept: application/json
Content-Type: application/json

{
  "rental_id": 125,
  "rental_date": "2021-12-05",
  "customer_id": 2,
  "return_date": "2021-12-25",
  "staff_id": 1
}

###