GET http://localhost:8080/v1/api/film/maude
Accept: application/json

###

GET http://localhost:8080/v1/api/film/ed chase
Accept: application/json

###

GET http://localhost:8080/v1/api/film/getFilm?title=ACADEMY DINOSAUR&actor=PENELOPE GUINESS
Accept: application/json
Content-Type: application/json

###
GET http://localhost:8080/v1/api/film/getFilmAll?page=1&size=5
Accept: application/json
Content-Type: application/json

###
