POST http://localhost:8080/v1/api/customer/post
Accept: application/json
Content-Type: application/json

{
  "store_id": 2,
  "first_name": "Mark",
  "last_name": "Hammil",
  "email": "mhmm@gmail.com",
  "address_id": 2,
  "active": 1
}
###

PUT http://localhost:8080/v1/api/customer
Accept: application/json
Content-Type: application/json

{
 "address": "1913 Hanoi Way",
 "address2": "",
 "district": "Alberta",
 "city_id": 361,
 "postal_code": "42399",
 "phone": "10655648674"
}

